
spring:
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MariaDBDialect
        hibernate:
            ddl-auto: validate
    datasource:
        url: jdbc:mariadb://localhost:3306/simple_board
        username: root
        password: 1234
        driver-class-name: org.mariadb.jdbc.Driver